blueprint:
  name: Philips Hue Dimmer Switch
  domain: automation  
  input:
    switch:
      name: Light switch
      selector:
        device:
          filter:
            - integration: zha
              manufacturer: Signify Netherlands B.V.
              model: RWL022
    target_lights:
      name: Target light entity
      selector:
        entity:
          filter:
            domain: light
triggers:
  - device_id: !input switch
    domain: zha
    type: remote_button_short_press
    subtype: turn_on
    trigger: device
    id: "on"
  - device_id: !input switch
    domain: zha
    type: remote_button_short_press
    subtype: turn_off
    trigger: device
    id: "off"
  - device_id: !input switch
    domain: zha
    type: remote_button_double_press
    subtype: turn_off
    trigger: device
    id: "off"
  - device_id: !input switch
    domain: zha
    type: remote_button_triple_press
    subtype: turn_off
    trigger: device
    id: "off"
  - device_id: !input switch
    domain: zha
    type: remote_button_quadruple_press
    subtype: turn_off
    trigger: device
    id: "off"
  - device_id: !input switch
    domain: zha
    type: remote_button_quintuple_press
    subtype: turn_off
    trigger: device
    id: "off"
  - device_id: !input switch
    domain: zha
    type: remote_button_short_press
    subtype: dim_up
    trigger: device
    id: dimUpShort
  - device_id: !input switch
    domain: zha
    type: remote_button_double_press
    subtype: dim_up
    trigger: device
    id: dimUpShort 
  - device_id: !input switch
    domain: zha
    type: remote_button_triple_press
    subtype: dim_up
    trigger: device
    id: dimUpShort
  - device_id: !input switch
    domain: zha
    type: remote_button_quadruple_press
    subtype: dim_up
    trigger: device
    id: dimUpShort 
  - device_id: !input switch
    domain: zha
    type: remote_button_quintuple_press
    subtype: dim_up
    trigger: device
    id: dimUpShort        
  - device_id: !input switch
    domain: zha
    type: remote_button_short_press
    subtype: dim_down
    trigger: device
    id: dimDownShort 
  - device_id: !input switch
    domain: zha
    type: remote_button_double_press
    subtype: dim_down
    trigger: device
    id: dimDownShort
  - device_id: !input switch
    domain: zha
    type: remote_button_triple_press
    subtype: dim_down
    trigger: device
    id: dimDownShort
  - device_id: !input switch
    domain: zha
    type: remote_button_quadruple_press
    subtype: dim_down
    trigger: device
    id: dimDownShort
  - device_id: !input switch
    domain: zha
    type: remote_button_quintuple_press
    subtype: dim_down
    trigger: device
    id: dimDownShort
conditions: []
variables: 
  dimStepPercentagePress: 25
actions:
  - choose:
      - conditions:
        - condition: trigger
          id:
            - "on"
        sequence:
          - action: light.toggle
            metadata: {}
            data: {}
            target: 
              entity_id: !input target_lights
      - conditions:
          - condition: trigger
            id:
              - "off"
        sequence:
          - choose:
            - conditions:
              - condition: numeric_state
                entity_id: !input target_lights
                attribute: color_temp_kelvin
                below: 2440   
              sequence:
                - action: light.turn_on
                  metadata: {}
                  data:
                    kelvin: 2702
                  target:
                    entity_id: !input target_lights
            - conditions:
              - condition: numeric_state
                entity_id: !input target_lights
                attribute: color_temp_kelvin
                above: 3999
              sequence:
                - action: light.turn_on
                  metadata: {}
                  data:
                    kelvin: 2439
                  target:
                    entity_id: !input target_lights 
            default:
              - action: light.turn_on
                metadata: {}
                data:
                  kelvin: 4000
                target:
                  entity_id: !input target_lights                  
      - conditions:
          - condition: trigger
            id:
              - "dimDownShort"
        sequence:
          - choose: 
            - conditions:
              - condition: numeric_state
                entity_id: !input target_lights
                attribute: brightness
                above: 65
              sequence:  
                - action: light.turn_on
                  metadata: {}
                  data:
                    brightness_step_pct: "{{ -(dimStepPercentagePress) }}" 
                  target:
                    entity_id: !input target_lights  
            default:
              - action: light.turn_on
                metadata: {}
                data:
                  brightness: 1
                target:
                  entity_id: !input target_lights        
      - conditions:
          - condition: trigger
            id:
              - "dimUpShort"
        sequence:
          - action: light.turn_on
            metadata: {}
            data:
              brightness_step_pct: "{{ dimStepPercentagePress }}"
            target:
              entity_id: !input target_lights                                         